### ISSUE TITLE
Who does what

### ISSUE THREAD

**Issue by Sandra8399** [Sandra8399/Seminair-g3#1]
Hi, since the presentation is due in about a week, we should divide who does what on the actual R code. There seem to be four main points to work on, do you have a preference, which of them you want to work on?

**Comment by Sandra8399** [comment]
In total we have:

- [ ] Import RNA-seq count data into R and perform filtering to remove low-expressed genes

- [ ] Perform statistical analysis to identify differentially expressed genes between the carcinoma and normal samples. Genes should be filtered on FDR and log2 fold change

- [ ] Perform over-representation analysis with the functions enrichGO and enrichKEGG in the clusterProfiler package. The key type for the genes in the dataset is SYMBOL. Note that enrichKEGG expects Entrez gene IDs (ENTREZID), so IDs need to be converted before analyzing KEGG pathways. The clusterProfiler package provides the convenient bitr function for this.

- [ ] Export the table with differentially expressed genes to Excel and create plots to visualize the results of the enrichment analysis. Examples of functions to use are cneplot, dotplot and treeplot. The last one depends on a term similarity matrix, which is calculated by calling pairwise_termsim on the enrichment analysis results

Say if you have any preference, but we need to get started soon.

**Comment by Zozansm** [comment]
Hi! I’d prefer to work on the last two tasks. Would you be okay with taking the first two tasks: importing/filtering the data and running the statistical analysis for DEGs? Let me know if that works for you, and we can get started! 😊

**Comment by Sandra8399** [comment]
Great, I'll get working on those two. I should have that done sometime today, latest tomorrow, I will post about it here to let you know. Ideally if you could have the last two tasks by early Wednesday, so we can get started on the presentation.
