### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by Sandra8399** [Sandra8399/Seminair-g3#2]
I've finished and uploaded the first part of the exercise, will let you know when I complete the second as well. If you think there's an issue with what I've written, let me know and I'll try to fix it.

**Comment by Sandra8399** [comment]
Completed the second part of the assignment. If there's any issues or concerns, let me know. Good luck on your part.

**Comment by Zozansm** [comment]
Ok thank you! I will check it and comeback to you if I have any comments

**Comment by Zozansm** [comment]
I have completed the enrichment analysis for the RNA-seq data, including GO Biological Processes and KEGG Pathways. The results were saved in Enrichment_Results.xlsx with separate sheets for GO and KEGG results. I also created and saved plots for the top 10 GO terms, KEGG pathways, and a GO term similarity tree as GO_Enrichment_Network.png, Top10_GO_Enrichment.png, Top10_KEGG_Pathways.png, and GO_Term_Similarity_Tree.png.

**Comment by Sandra8399** [comment]
Saw it, seems good to me. I think you can push the changes to the main branch, since we don't need to make changes.

**Comment by Sandra8399** [comment]
I'm currently working on the documentation, once it's done I'll post it on a separate branch, so you can look at it before merge.

**Comment by Zozansm** [comment]
I will merge now the branch with the main.

**Comment by Zozansm** [comment]
I made a new input directory and moved the input files into them check the changes in the branch if you are ok with it I will merge it with the main :)

**Comment by Sandra8399** [comment]
Does it work as is or do you need to specify, in the program, that the files are in a different folder?
Otherwise no issue from me

**Comment by Zozansm** [comment]
I pushed some changes to the branch like documentation and input file check the changes if you confirm I can then merge it with the main
