### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by Sandra8399** [Sandra8399/Seminair-g3#3]
We're still working on some stuff, like the documentation, but we should talk about the presentation. I posted it here a while back, so we can work on it at the same time & them just merge. So we just need to decide who does what.

**Comment by Sandra8399** [comment]
I was thinking we could split intro & collaboration, since we both did parts that belong on that slide. That leaves Git repository, programming practices, documentation and case study.

**Comment by Zozansm** [comment]
As we discussed the introduction and collaboration will be presented by both of us, you can do Git repository, programming practices and I can do the documentation and case study.
